---
title: "Distributions"
author: "Javiera Rudolph"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
# knitr::opts_chunk$set(fig.width=12, fig.height=6)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r message=FALSE, warning=FALSE}
library(aracari)
library(dplyr)
library(tidyr)
library(ggplot2)
library(cowplot)
library(fitdistrplus)

```


```{r include=FALSE}
set.seed(20211207)

# Data ----------------------------------------------------
# The script for this data is in the data-raw folder
load("data/ptpl.rda")

ptpl %>%
  filter(., mpm != 0) -> ptpl
```

# Figure 1  

```{r Figure1, fig.height=6, fig.width=4}
# Figure 1 ---------------------------------------------
# Distribution of velocities at the different pooling levels

ptpl %>%
  ggplot(., aes((x = mpm))) +
  #geom_line(aes(x = mpm, group = id), stat = "density", alpha = 0.4) +
  # geom_line(aes(x = mpm, group = fam_g), stat = "density", alpha = 0.4,
  #           color = "blue") +
  geom_line(stat = "density", color = "#1191d1", lwd = 1) +
  geom_vline(xintercept = 0, color = "grey") +
  geom_hline(yintercept = 0, color = "grey") +
  labs(y = "Density", x = "Velocity in m/min") +
  theme_classic() -> cp_lines

ptpl %>%
  ggplot(., aes((x = mpm))) +
  geom_line(aes(x = mpm, group = id), stat = "density", alpha = 0.4) +
  # geom_line(aes(x = mpm, group = fam_g), stat = "density", alpha = 0.4,
  #           color = "blue") +
  #geom_line(stat = "density", color = "#1191d1", lwd = 1) +
  geom_vline(xintercept = 0, color = "grey") +
  geom_hline(yintercept = 0, color = "grey") +
  labs(y = "Density", x = "Velocity in m/min") +
  theme_classic() -> pp_lines

ptpl %>%
  ggplot(., aes((x = mpm))) +
  #geom_line(aes(x = mpm, group = id), stat = "density", alpha = 0.4) +
  geom_line(aes(x = mpm, group = fam_g), stat = "density", alpha = 0.4) +
  #geom_line(stat = "density", color = "#1191d1", lwd = 1) +
  geom_vline(xintercept = 0, color = "grey") +
  geom_hline(yintercept = 0, color = "grey") +
  labs(y = "Density", x = "Velocity in m/min") +
  theme_classic() -> np_lines

plot_grid(cp_lines, pp_lines, np_lines, nrow = 3)
```  


# Figure X - angles

```{r fig.width=8, fig.height=6}
p1_angles <- ptpl %>% 
  drop_na(rel.angle) %>% 
  mutate(d.angle = ifelse(rel.angle > 0, rel.angle * 180/pi,
                          rel.angle * 180/pi + 360)) %>% 
  ggplot(., aes(x = d.angle)) +
  geom_histogram(color = "grey", fill = "grey") +
  coord_polar(theta = "x", start = -pi/2, direction = -1) +
  scale_x_continuous(breaks = seq(0, 360, 30), limits = c(0, 360)) +
  theme_minimal() +
  theme(axis.title = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "none") +
  labs(title = "Complete pooling")


p2_angles <- ptpl %>% 
  drop_na(rel.angle) %>% 
  mutate(d.angle = ifelse(rel.angle > 0, rel.angle * 180/pi,
                          rel.angle * 180/pi + 360)) %>% 
  ggplot(., aes(x = d.angle)) +
  geom_histogram(color = "grey", fill = "grey") +
  coord_polar(theta = "x", start = -pi/2, direction = -1) +
  scale_x_continuous(breaks = seq(0, 360, 30), limits = c(0, 360)) +
  theme_minimal() +
  theme(axis.title = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "none") +
  facet_wrap(~fam_g, nrow = 2) +
  theme(axis.text = element_blank()) +
  labs(title = "Partial pooling")

p3_angles <- ptpl %>% 
  drop_na(rel.angle) %>% 
  mutate(d.angle = ifelse(rel.angle > 0, rel.angle * 180/pi,
                          rel.angle * 180/pi + 360),
         B_id = paste0("B", id)) %>% 
  ggplot(., aes(x = d.angle)) +
  geom_histogram(color = "grey", fill = "grey") +
  coord_polar(theta = "x", start = -pi/2, direction = -1) +
  scale_x_continuous(breaks = seq(0, 360, 30), limits = c(0, 360)) +
  theme_minimal() +
  theme(axis.title = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "none") +
  facet_wrap(~B_id, nrow = 2) +
  theme(axis.text = element_blank()) +
  labs(title = "No pooling")

plot_grid(plot_grid(p1_angles, p2_angles), p3_angles, nrow = 2)

```

# Fits 

```{r}
load("Ch2_distributions/Ch2_fits.RData")
```


```{r}
reg_fits_info %>% 
  dplyr::select(., dist, dBIC, ID, model) %>% 
  distinct() %>% 
  filter(., dBIC == 0) -> bestmodel

#bestmodel
```

```{r fig.width=12}

cp.boot.fits %>%
  dplyr::select(., bic, dist, dBIC, boot) %>%
  group_by(boot) %>%
  distinct() %>%
  ungroup() %>%
  filter(dBIC == 0) %>%
  count(dist) %>%
  mutate(prcnt_support = n/nboots) %>%
  mutate(model = "CP") %>%
  ggplot(., aes(x = model, y = prcnt_support, fill = dist)) +
  geom_col() +
  theme(legend.position = "none") +
  geom_label(data = bestmodel %>% filter(., model == "CP"),
             aes(x = model, y = -0.05, label = dist)) -> cp.fit

pp.boot.fits %>%
  dplyr::select(., bic, dist, dBIC, fgroup, boot) %>%
  group_by(fgroup, boot) %>%
  distinct() %>%
  group_by(fgroup) %>%
  filter(dBIC == 0) %>%
  count(dist) %>%
  mutate(prcnt_support = n/nboots) %>%
  ggplot(., aes(x = fgroup, y = prcnt_support, fill = dist)) +
  geom_col() +
  theme(legend.position = "none") +
  geom_label(data = bestmodel %>% filter(., model == "PP"),
             aes(x = ID, y = -0.05, label = dist))-> pp.fit

np.boot.fits %>%
  dplyr::select(., bic, dist, dBIC, individual, boot) %>%
  group_by(individual, boot) %>%
  distinct() %>%
  group_by(individual) %>%
  filter(dBIC == 0) %>%
  count(dist) %>%
  mutate(prcnt_support = n/nboots) %>%
  ggplot(., aes(x = individual, y = prcnt_support, fill = dist)) +
  geom_col() +
  geom_label(data = bestmodel %>% filter(., model == "NP"),
             aes(x = ID, y = -0.05, label = dist)) -> np.fit

legend <- get_legend(np.fit + theme(legend.position = "bottom"))

plot_grid(cp.fit, pp.fit, 
          np.fit + theme(legend.position = "none"), 
          ncol = 3, rel_widths = c(0.4,1,1.4)) -> col_grid

plot_grid(col_grid, legend, nrow = 2, rel_heights = c(1, 0.1))

```

```{r}
# Difference to the second best model

reg_fits_info %>% 
  dplyr::select(., dist, dBIC, ID, model) %>% 
  distinct() %>% 
  ggplot(., aes(x = ID, y = dBIC, color = dist)) +
  #facet_wrap(~model) +
  geom_point()

```


Calculate the BIC for the models:

```{r}
reg_fits_info %>% 
  dplyr::select(model, ID, dist, loglik, n, kpars) %>% 
  distinct() %>% 
  group_by(model, dist) %>% 
  summarise(BIC = log(sum(n))*sum(kpars) - 2 * sum(loglik)) %>% 
  mutate(deltaBIC_withinmodels = signif(BIC - min(BIC), 3)) %>% 
  ungroup() %>% 
  mutate(deltaBIC_acrossmodels = signif(BIC - min(BIC), 3)) %>% 
  ggplot(., aes(x = model, y = BIC, color = dist)) +
  geom_point()
```

