---
title: "Extreme Value Chapter 3"
author: "Javiera Rudolph"
output:
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
# knitr::opts_chunk$set(fig.width=12, fig.height=6)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r libraries}
library(dplyr)
library(ggplot2)
library(cowplot)
library(tidyr)
library(purrr)
library(MetBrewer)
library(stringr)
library(latex2exp)
```

```{r loadData}
path <- "Ch3_samplesize/original/"
load(paste0(path, "mixturesamples.RData"))
load(paste0(path, "nreps_mles_df.RData"))
load(paste0(path, "nonpar_glm.RData"))
load(paste0(path, "par_glm.RData"))
load(paste0(path, "GP_runs.RData"))

source("Ch3_samplesize/Ch3_functions.R")
```

```{r}
# Color palettes

pal_sampsize <- met.brewer("Hokusai3", n = 6)
pal_threshold <- met.brewer("Derain", n = 7)
pal_mixture <- met.brewer("Hokusai1", n = 4)
theta_color <- "steelblue"
pal_bias <- met.brewer("Lakota", n=5)

```

```{r}
# Stuff needed for plots later

# TEST VALUES --------------------------------------
## Thresholds ----------------
# Thresholds based on quantiles: because when we have a sample, we still don't know the truth
# But we can know the quantiles of our sample.
# summary(truth_df$x_samps)
# thresh_tests <- round(quantile(truth_df$x_samps, c(0.5, 0.75, 0.9, 0.99, 0.999, 0.9999), names = FALSE))
tru_n <- 50000
pis <- c( 0.1, 0.2, 0.3, 0.4)
w_samp_sizes <- pis*tru_n

thresh_tests <- c(50, 100, 150, 250, 500, 750, 1000)
tibble(thresh_tests) %>%
  mutate(n_overthresh = map_dbl(1:length(thresh_tests),
                                function(y) length(which(truth_df$x_samps >= thresh_tests[y]))),
         theta = n_overthresh/tru_n) -> thetas

## Sample sizes --------------------
samp_n_tests <- c(80, 200, 500, 800, 1000, 1600)

all_test_combos <- data.frame(expand.grid(thresh_tests = thresh_tests, samp_n_tests = samp_n_tests))
```

# Figure 1 

The mixture distribution used to generate the data: 

```{r Mixtures_FX}
# Figure 1 function to make multiples

mixtures_plot_fx <- function(pars = pars, dens_cols = dens_cols, pis = pis, desired_means = desired_means, desired_sds = desired_sds, weighted = FALSE){
  
  if(weighted == TRUE){
    lnorm_densities <- purrr::map(1:4, function(y) stat_function(fun = dlnorm, args = list(meanlog = pars$meanlog[y], sdlog = pars$sdlog[y]), color = dens_cols[y], size=pis[y]*5, alpha = 0.8))
  } else{
    lnorm_densities <- purrr::map(1:4, function(y) stat_function(fun = dlnorm, args = list(meanlog = pars$meanlog[y], sdlog = pars$sdlog[y]), color = dens_cols[y], size=1, alpha = 0.8))
  }
  
  # Plot density components of the mixture
  ggplot() +
    lnorm_densities +
    theme_minimal(base_size = 6) +
    labs(y = "Density") +
    lims(x = c(0, 150)) -> densities_plot
  # densities_plot

  # Plot the means and sd for each of the curves
  data.frame(desired_means, desired_sds, gID = factor(1:4)) %>%
    mutate(lo = desired_means - desired_sds,
           hi = desired_means + desired_sds) %>%
    ggplot(., aes(x = gID, y = desired_means, color = gID)) +
    geom_point(size = 2) +
    geom_errorbar(aes(ymin = lo, ymax = hi), width = 0.1, size = 1) +
    scale_color_manual(values = dens_cols) +
    labs(y = "Mean +/- SD") +
    theme_minimal(base_size = 6) +
    theme(axis.title.x = element_blank(),
          axis.text.x = element_blank(),
          legend.position = "none") -> means_sd_plot
  # means_sd_plot

  # Align these plots to have multiple panels lates
  plot_grid(NULL, means_sd_plot, densities_plot, rel_widths = c(0.1, 1, 3), nrow = 1)
}

bias_bxplot_fx <- function(data){
  data %>% 
  dplyr::select(., thresh_tests, samp_n_tests, gp_theta_hat, gp_theta_bar, theta) %>%
  mutate(original = log(gp_theta_hat/theta),
         corrected = log(gp_theta_bar/theta)) %>%
  pivot_longer(., cols = c(original, corrected), names_to = "type", values_to = "theta_val") %>%
  drop_na() %>%
  mutate(thresh_tests = factor(thresh_tests),
         samp_n_tests = factor(samp_n_tests)) %>% 
  mutate(labelsamp = paste("n =", samp_n_tests),
         labelsamp = factor(labelsamp, levels = c("n = 80", "n = 200", "n = 500", "n = 800", "n = 1000", "n = 1600"))) %>%
  ggplot(., aes(x = thresh_tests, y = theta_val, color = type, fill = type)) +
  facet_wrap(~labelsamp, nrow = 1) +
  geom_boxplot() +
  scale_color_manual(values = dens_cols[c(1,4)], name = "Bias") +
  scale_fill_manual(values = dens_cols[c(2,3)], name = "Bias") +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  labs(y = TeX(r'($log(\hat{\theta} / \theta)$)'), x = "Distance Level Estimated") +
  theme_bw()
}

```

```{r fig.width=4, fig.height=5}
# Scenarios:
pis <- c( 0.1, 0.2, 0.3, 0.4)
dens_cols <- pal_mixture

# SAME SD INCREASING MEAN ------------------------------
desired_means <- c(30, 40, 50, 60)
desired_sds <- c(25, 25, 25, 25)
pars <- desired_mean_sd(mu_x = desired_means, sd_x = desired_sds)

A1 <- mixtures_plot_fx(pars = pars, dens_cols = dens_cols, pis = pis, desired_means = desired_means, desired_sds = desired_sds)

dir_scenario <- "ain1_samesd_upmean"
load(paste0("Ch3_samplesize/", dir_scenario, "/allin1df.RData"))

B1 <- bias_bxplot_fx(allin1df)

# SAME MEAN INCREASING SD ------------------------------
desired_means <- c(30, 30, 30, 30)
desired_sds <- c(20, 30, 40, 50)
pars <- desired_mean_sd(mu_x = desired_means, sd_x = desired_sds)

A2 <- mixtures_plot_fx(pars = pars, dens_cols = dens_cols, pis = pis, desired_means = desired_means, desired_sds = desired_sds)

# INCREASING SD INCREASING MEAN ------------------------------
desired_means <- c(30, 40, 50, 60)
desired_sds <- c(20, 30, 40, 50)
pars <- desired_mean_sd(mu_x = desired_means, sd_x = desired_sds)

A3 <- mixtures_plot_fx(pars = pars, dens_cols = dens_cols, pis = pis, desired_means = desired_means, desired_sds = desired_sds)

# DECREASING BOTH ------------------------------
desired_means <- c(60, 50, 40, 30)
desired_sds <- c(50, 40, 30, 20)
pars <- desired_mean_sd(mu_x = desired_means, sd_x = desired_sds)

A4 <- mixtures_plot_fx(pars = pars, dens_cols = dens_cols, pis = pis, desired_means = desired_means, desired_sds = desired_sds)

#INCREASING MEANS DECRESING SD --------------------------------------
desired_means <- c(30, 35, 40, 50)
desired_sds <- c(50, 40, 35, 30)
pars <- desired_mean_sd(mu_x = desired_means, sd_x = desired_sds)

A5 <- mixtures_plot_fx(pars = pars, dens_cols = dens_cols, pis = pis, desired_means = desired_means, desired_sds = desired_sds)


plot_grid(A1, A2, A3, A4, ncol = 1, labels = "AUTO", label_size = 8)
ggsave("Ch3_samplesize/Figures/Many_mixtures.png")
```

```{r fig.width=6, fig.height=3}
desired_means <- c(28, 32, 40, 50)
desired_sds <- c(49.7, 39.9, 33.3, 31.1)
pars <- desired_mean_sd(mu_x = desired_means, sd_x = desired_sds)
# These are the weights for the distribution
pis <- c( 0.1, 0.2, 0.3, 0.4)

# The color associated to each mixture component
dens_cols <- c("#264653", "#2a9d8f", "#f4a261", "#e76f51")
# dens_cols <- pal_mixture

# Build the densities for plotting
weighted_densities <- purrr::map(1:4, function(y) stat_function(fun = dlnorm, args = list(meanlog = pars$meanlog[y], sdlog = pars$sdlog[y]), color = dens_cols[y], size=1, alpha = 0.8))

# Plot density components of the mixture
ggplot() +
  weighted_densities +
  theme_bw(base_size = 7) +
  labs(y = "Component Densities") +
  lims(x = c(0, 150)) -> densities_plot

# Plot the means and sd for each of the curves
data.frame(desired_means, desired_sds, gID = factor(1:4)) %>%
  mutate(lo = desired_means - desired_sds,
         hi = desired_means + desired_sds) %>%
  ggplot(., aes(x = gID, y = desired_means, color = gID)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = lo, ymax = hi), width = 0.1, size = 1) +
  scale_color_manual(values = dens_cols) +
  labs(y = "Mean +/- SD") +
  theme_bw(base_size = 7) +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        legend.position = "none") -> means_sd_plot


tru_tail <- data.frame(values = truth_df$x_samps, y = 100) %>% arrange(desc(values)) %>% filter(values >=50)

# Histogram plus the points in the tail.
truth_df %>%
  ggplot(., aes(x = x_samps)) +
  geom_histogram(bins = 100) +
  geom_point(data = tru_tail[1:50,], aes(x = values, y = y), color = "grey47", alpha = 0.9, size = 1) +
  geom_vline(xintercept = thresh_tests, color = dens_cols[4], linetype = "dashed", size = 0.3) +
  labs(y = "Frequency", x = "Distance") +
  #lims(x = c(0, 150)) +
  theme_bw(base_size = 7) -> truth_hist
# truth_hist

# Density curve for the mixture based on the 50k samples.
truth_df %>%
  ggplot(., aes(x = x_samps)) +
  geom_density() +
  labs(y = "Mixture Density", x = "Distance") +
  lims(x = c(0, 150), y = c(0,0.05)) +
  theme_bw(base_size = 7) +
  theme(axis.title.x = element_blank()) -> truth_density
# truth_density

# Visualize both in one frame
# plot_grid(truth_hist, truth_density)

## Figure 1 -----------------------------


top_row <- plot_grid(means_sd_plot, densities_plot, truth_density, nrow = 1, rel_widths = c(1,2,2), labels = "AUTO", label_size = 8)

plot_grid(top_row, truth_hist, nrow = 2, labels = c("", "D"), label_size = 8)
ggsave("Ch3_samplesize/Figures/Figure1.png")

```


# Table 1

The actual values of theta for the 50k sample we took from the mixture distribution:  

```{r}
thetas %>% 
  knitr::kable()
# write.csv(thetas, file = "Ch3_samplesize/Figures/table1.csv")
```


# Figure 2

```{r eval=FALSE, fig.width=5, fig.height=2.5}
# thetas %>% 
#   ggplot(., aes(x = thresh_tests, y = theta)) +
#   geom_point(size = 4, shape = 18, color = theta_color) +
#   labs(x = "Long-distance level", y = "Theta") +
#   theme_bw() -> a

thetas %>% 
  ggplot(., aes(x = thresh_tests, y = log(theta))) +
  geom_point(size = 3, shape = 18, color = theta_color) +
  labs(x = "Distance level", y = "log(theta)") +
  scale_x_continuous(breaks = thresh_tests) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30)) -> b
b
# plot_grid(a, b, ncol = 2)


```

```{r eval = FALSE, fig.width=6, fig.height=4}
nreps_mles_df %>% 
  ggplot(., aes(x = thresh_tests, y = log_St_hat)) +
  # facet_wrap(~samp_n_tests, nrow = 1) +
  geom_point(alpha = 0.8, size = 3, color = "grey27") +
  labs(x = "Long-distance level", y = "Estimated thetas", title = "Simple Lomax") +
  scale_x_continuous(breaks = thresh_tests) +
  theme_bw() -> a

nreps_mles_df %>% 
  ggplot(., aes(x = thresh_tests, y = log_St_hat2)) +
  # facet_wrap(~samp_n_tests, nrow = 1) +
  geom_point(alpha = 0.8, size = 3, color = "grey27") +
  labs(x = "Long-distance level", y = "Estimated thetas", title = "GLM Lomax") +
  scale_x_continuous(breaks = thresh_tests) +
  theme_bw() -> b

plot_grid(a, b, nrow = 2)

```

```{r eval = FALSE, fig.width=6, fig.height=4}
nreps_mles_df %>% 
  ggplot(., aes(x = thresh_tests, y = log_St_hat)) +
  # facet_wrap(~samp_n_tests, nrow = 1) +
  geom_jitter(alpha = 0.8, size = 3, color = "grey27") +
  labs(x = "Long-distance level", y = "Estimated thetas", title = "Simple Lomax") +
  scale_x_continuous(breaks = thresh_tests) +
  theme_bw() -> a

nreps_mles_df %>% 
  ggplot(., aes(x = thresh_tests, y = log_St_hat2)) +
  # facet_wrap(~samp_n_tests, nrow = 1) +
  geom_jitter(alpha = 0.8, size = 3, color = "grey27") +
  labs(x = "Long-distance level", y = "Estimated thetas", title = "GLM Lomax") +
  scale_x_continuous(breaks = thresh_tests) +
  theme_bw() -> b

plot_grid(a, b, nrow = 2)
```

```{r eval = FALSE, fig.width=8, fig.height=4}
nreps_mles_df %>% 
  ggplot(., aes(x = thresh_tests, y = log_St_hat)) +
  # facet_wrap(~samp_n_tests, nrow = 1) +
  geom_jitter(alpha = 0.8, size = 3, aes(color = factor(samp_n_tests))) +
  scale_color_manual(values = pal_sampsize) +
  labs(x = "Long-distance level", y = "Estimated thetas", title = "Simple Lomax") +
  scale_x_continuous(breaks = thresh_tests) +
  theme_bw() +
  theme(legend.position = "none") -> a

nreps_mles_df %>% 
  ggplot(., aes(x = thresh_tests, y = log_St_hat2)) +
  # facet_wrap(~samp_n_tests, nrow = 1) +
  geom_jitter(alpha = 0.8, size = 3, aes(color = factor(samp_n_tests))) +
  scale_color_manual(values = pal_sampsize) +
  labs(x = "Long-distance level", y = "Estimated thetas", title = "GLM Lomax") +
  scale_x_continuous(breaks = thresh_tests) +
  theme_bw() +
  theme(legend.position = "right") + 
  guides(color = guide_legend(title = "Sample Size")) -> b

ableg <- get_legend(b)

abplot <- plot_grid(a, b + theme(legend.position = "none"), nrow = 2)

plot_grid(abplot, ableg, ncol = 2, rel_widths = c(1, 0.3))

```

```{r eval = FALSE, fig.width=8, fig.height=4}
nreps_mles_df %>% 
  mutate(samp_n_tests = factor(samp_n_tests),
         thresh_tests = factor(thresh_tests)) %>% 
  ggplot(., aes(x = thresh_tests, y = log_St_hat, fill = samp_n_tests, color = samp_n_tests)) +
  # facet_wrap(~samp_n_tests, nrow = 1) +
  geom_boxplot(alpha = 0.9) +
  scale_fill_manual(values = pal_sampsize) +
  scale_color_manual(values = pal_sampsize) +
  labs(x = "Long-distance level", y = "Theta hat", title = "Simple Lomax") +
  theme_bw() +
  theme(legend.position = "none") -> a

nreps_mles_df %>% 
  mutate(samp_n_tests = factor(samp_n_tests),
         thresh_tests = factor(thresh_tests)) %>% 
  ggplot(., aes(x = thresh_tests, y = log_St_hat2, fill = samp_n_tests, color = samp_n_tests)) +
  # facet_wrap(~samp_n_tests, nrow = 1) +
  geom_boxplot(alpha = 0.9) +
  scale_fill_manual(values = pal_sampsize, name = "Sample Size") +
  scale_color_manual(values = pal_sampsize, name = "Sample Size") +
  labs(x = "Long-distance level", y = "Theta hat", title = "GLM Lomax") +
  theme_bw() +
  theme(legend.position = "right") -> b

ableg <- get_legend(b)

abplot <- plot_grid(a, b + theme(legend.position = "none"), nrow = 2)

plot_grid(abplot, ableg, ncol = 2, rel_widths = c(1, 0.3))

```


```{r fig.width=6, fig.height=4}

# See it compared to the original theta
nreps_mles_df %>% 
  mutate(samp_n_tests = factor(samp_n_tests),
         thresh_tests = factor(thresh_tests)) %>% 
  ggplot(., aes(x = thresh_tests, y = log_St_hat - log(theta), fill = samp_n_tests, color = samp_n_tests)) +
  # facet_wrap(~samp_n_tests, nrow = 1) +
  geom_boxplot(alpha = 0.9) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  scale_fill_manual(values = pal_sampsize) +
  scale_color_manual(values = pal_sampsize) +
  labs(x = " ", y = TeX(r'($log(\hat{\theta} / \theta)$)'), subtitle = "Simple Lomax") +
  theme_bw(base_size = 8) +
  theme(legend.position = "none") -> a

nreps_mles_df %>% 
  mutate(samp_n_tests = factor(samp_n_tests),
         thresh_tests = factor(thresh_tests)) %>% 
  ggplot(., aes(x = thresh_tests, y = log_St_hat2 - log(theta), fill = samp_n_tests, color = samp_n_tests)) +
  # facet_wrap(~samp_n_tests, nrow = 1) +
  geom_boxplot(alpha = 0.9) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  scale_fill_manual(values = pal_sampsize, name = "Sample Size") +
  scale_color_manual(values = pal_sampsize, name = "Sample Size") +
  labs(x = "", y = TeX(r'($log(\hat{\theta} / \theta)$)'), subtitle = "GLM Lomax") +
  theme_bw(base_size = 8) +
  theme(legend.position = "right") -> b

ableg <- get_legend(b)

GP_mles %>% 
    mutate(samp_n_tests = factor(samp_n_tests),
         thresh_tests = factor(thresh_tests)) %>% 
  ggplot(., aes(x = thresh_tests, y = log(quant_theta/theta), fill = samp_n_tests, color = samp_n_tests)) +
  # facet_wrap(~samp_n_tests, nrow = 1) +
  geom_boxplot(alpha = 0.9) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  scale_fill_manual(values = pal_sampsize) +
  scale_color_manual(values = pal_sampsize) +
  labs(x = "Distance level", y = TeX(r'($log(\hat{\theta} / \theta)$)'), subtitle = "Generalized Pareto") +
  theme_bw(base_size = 8) +
  theme(legend.position = "none") -> c

abplot <- plot_grid(a, b + theme(legend.position = "none"), c, nrow = 3, labels = "AUTO", label_size = 8)

plot_grid(abplot, ableg, ncol = 2, rel_widths = c(1, 0.2))
ggsave("Ch3_samplesize/Figures/Figure2.png")

```


```{r eval=FALSE, fig.width=10, fig.height=5}


# See it compared to the original theta
nreps_mles_df %>% 
  filter(., thresh_tests < 500) %>% 
  mutate(samp_n_tests = factor(samp_n_tests),
         thresh_tests = factor(thresh_tests)) %>% 
  ggplot(., aes(x = thresh_tests, y = log_St_hat - log(theta), fill = samp_n_tests, color = samp_n_tests)) +
  # facet_wrap(~samp_n_tests, nrow = 1) +
  geom_boxplot(alpha = 0.9) +
  geom_hline(yintercept = 0, color = "red") +
  scale_fill_manual(values = pal_sampsize) +
  scale_color_manual(values = pal_sampsize) +
  labs(x = "Distance level", y = TeX(r'($log(\hat{\theta} / \theta)$)'), subtitle = "Simple Lomax") +
  theme_bw() +
  theme(legend.position = "none") -> a1

nreps_mles_df %>% 
  filter(., thresh_tests >= 500) %>% 
  mutate(samp_n_tests = factor(samp_n_tests),
         thresh_tests = factor(thresh_tests)) %>% 
  ggplot(., aes(x = thresh_tests, y = log_St_hat - log(theta), fill = samp_n_tests, color = samp_n_tests)) +
  # facet_wrap(~samp_n_tests, nrow = 1) +
  geom_boxplot(alpha = 0.9) +
  geom_hline(yintercept = 0, color = "red") +
  scale_fill_manual(values = pal_sampsize) +
  scale_color_manual(values = pal_sampsize) +
  labs(x = "Distance level", y = " ", subtitle = " ") +
  theme_bw() +
  theme(legend.position = "none") -> a2

a <- plot_grid(a1, a2, ncol = 2)

nreps_mles_df %>% 
  filter(., thresh_tests < 500) %>% 
  mutate(samp_n_tests = factor(samp_n_tests),
         thresh_tests = factor(thresh_tests)) %>% 
  ggplot(., aes(x = thresh_tests, y = log_St_hat2 - log(theta), fill = samp_n_tests, color = samp_n_tests)) +
  # facet_wrap(~samp_n_tests, nrow = 1) +
  geom_boxplot(alpha = 0.9) +
  geom_hline(yintercept = 0, color = "red") +
  scale_fill_manual(values = pal_sampsize, name = "Sample Size") +
  scale_color_manual(values = pal_sampsize, name = "Sample Size") +
  labs(x = "Distance level", y = TeX(r'($log(\hat{\theta} / \theta)$)'), subtitle = "GLM Lomax") +
  theme_bw() +
  theme(legend.position = "none") -> b1

nreps_mles_df %>% 
  filter(., thresh_tests >= 500) %>% 
  mutate(samp_n_tests = factor(samp_n_tests),
         thresh_tests = factor(thresh_tests)) %>% 
  ggplot(., aes(x = thresh_tests, y = log_St_hat2 - log(theta), fill = samp_n_tests, color = samp_n_tests)) +
  # facet_wrap(~samp_n_tests, nrow = 1) +
  geom_boxplot(alpha = 0.9) +
  geom_hline(yintercept = 0, color = "red") +
  scale_fill_manual(values = pal_sampsize, name = "Sample Size") +
  scale_color_manual(values = pal_sampsize, name = "Sample Size") +
  labs(x = "Distance level", y = " ", subtitle = " ") +
  theme_bw() +
  theme(legend.position = "none") -> b2


b <- plot_grid(b1, b2, ncol = 2)

ableg <- get_legend(b1 + theme(legend.position = "right"))

abplot <- plot_grid(a, b, nrow = 2, labels = c("A", "B"))

plot_grid(abplot, ableg, ncol = 2, rel_widths = c(1, 0.2))

```



# Figure 3
Introduce the numerical estimation thing with the simple lomax: 

```{r fig.width=6, fig.height=3}
nreps_mles_df %>% 
  ggplot()+
  geom_point(aes(x = alpha_star, y = k_star, color = "Simple Lomax"), size = 4, alpha = 0.5) +
  geom_point(aes(x = alpha_glm, y = k_glm, color = "Lomax GLM"), size = 4, alpha = 0.5) +
  scale_y_log10() +
  scale_x_log10() +
  scale_color_manual(values = c("grey20", "dodgerblue4"), name = "") +
  labs(x = "Log(alpha)", y = "Log(k)") +
  theme_bw() +
  theme(legend.position = "bottom") -> a

nreps_mles_df %>% 
  mutate(labelsamp = paste("n =", samp_n_tests),
         labelsamp = factor(labelsamp, levels = c("n = 80", "n = 200", "n = 500", "n = 800", "n = 1000", "n = 1600"))) %>% 
  ggplot()+
  facet_wrap(~labelsamp) +
  geom_point(aes(x = alpha_star, y = k_star, color = "Simple Lomax"), size = 4, alpha = 0.5) +
  geom_point(aes(x = alpha_glm, y = k_glm, color = "Lomax GLM"), size = 4, alpha = 0.5) +
  scale_y_log10() +
  scale_x_log10() +
  scale_color_manual(values = c("grey20", "dodgerblue4"), name = "") +
  labs(x = "Log(alpha)", y = "Log(k)") +
  theme_bw() +
  theme(legend.position = "none",
        axis.text = element_blank()) -> b

ableg <- get_legend(a)

top <- plot_grid(a + theme(legend.position = "none"), b, ncol = 2, labels = "AUTO", label_size = 8)

plot_grid(top, ableg, nrow = 2, rel_heights = c(1, 0.1))
ggsave("Ch3_samplesize/Figures/Figure3.png")


```

# Figure 4

Bias correction

```{r eval = FALSE, fig.height=2.5, fig.width=5}
nreps_mles_df %>% 
  mutate(samp_n_tests = factor(samp_n_tests),
         thresh_tests = factor(thresh_tests)) %>% 
  group_by(thresh_tests, samp_n_tests) %>% 
  summarize(Eval_theta_hat = mean(log_St_hat2),
            theta = mean(theta),
            bias = Eval_theta_hat - theta) %>% 
  ggplot(., aes(y = bias, x = thresh_tests)) +
  geom_jitter(aes(color = samp_n_tests), size = 3, alpha = 0.9, width = 0.1) +
  geom_hline(yintercept = 0, color = "grey") +
  scale_color_manual(values = pal_sampsize, name = "Sample Size") +
  labs(x = "Distance level", y = "Bias", subtitle = "GLM Lomax") +
  theme_bw()


# 
# nreps_mles_df %>% 
#   mutate(samp_n_tests = factor(samp_n_tests),
#          thresh_tests = factor(thresh_tests),
#          theta_diff= log_St_hat2 - theta) %>% 
#   group_by(thresh_tests, samp_n_tests) %>% 
#   summarize(Eval_theta_hat = mean(log_St_hat2),
#             MSE = mean(theta_diff)^2,
#             theta = mean(theta),
#             bias = Eval_theta_hat - theta) %>% 
#   ggplot(., aes(y = MSE, x = thresh_tests)) +
#   geom_jitter(aes(color = samp_n_tests), size = 3, alpha = 0.9, width = 0.1) +
#   geom_hline(yintercept = 0, color = "red") +
#   scale_color_manual(values = pal_sampsize, name = "Sample Size") +
#   labs(x = "Long-distance level", y = "MSE", title = "GLM Lomax") +
#   theme_bw()
  
```


```{r}

# long_corr_df %>% 
#   group_by(thresh_tests, samp_n_tests, type) %>% 
#   summarise(meanval = mean(value)) %>% 
#   ungroup() %>% 
#   right_join(., thetas[, c(1,3)]) %>% 
#   mutate(thresh_tests = factor(thresh_tests)) -> means_df

par_glm %>% 
  mutate(Original = theta_hat - theta,
         Corrected = theta_bar - theta) %>% 
  dplyr::select(thresh_tests, samp_n_tests, Original, Corrected) %>% 
  pivot_longer(cols = c(Original, Corrected), names_to = "type") %>% 
  filter(., !is.infinite(value)) %>% 
  mutate(correctiontype = "Parametric") -> corr_a

nonpar_glm %>% 
  mutate(Original = theta_hat - theta,
         Corrected = theta_bar - theta) %>% 
  dplyr::select(thresh_tests, samp_n_tests, Original, Corrected) %>% 
  pivot_longer(cols = c(Original, Corrected), names_to = "type") %>% 
  filter(., !is.infinite(value)) %>% 
  mutate(correctiontype = "Nonparametric") -> corr_b


correction_df <- rbind.data.frame(corr_a, corr_b)

```

```{r eval = FALSE, fig.width=12, fig.height=6}

lowlabs <- paste0("n = ", samp_n_tests[1:6], "-lower")
extlabs <- paste0("n = ", samp_n_tests[1:6], "-extremes")

nonpar_glm %>% 
  mutate(Original = theta_hat - theta,
         Corrected = theta_bar - theta) %>% 
  dplyr::select(thresh_tests, samp_n_tests, Original, Corrected) %>% 
  pivot_longer(cols = c(Original, Corrected), names_to = "type") %>% 
  filter(., !is.infinite(value)) %>% 
  mutate(thresholdsep = factor(ifelse(thresh_tests<500, "lower", "extremes"), levels = c("lower", "extremes")),
         onelinelabel = paste0("n = ", samp_n_tests, "-", thresholdsep),
         onelinelabel = factor(onelinelabel, levels = c(lowlabs, extlabs)),
         samp_n_tests = factor(samp_n_tests),
         thresh_tests = factor(thresh_tests)) %>% 
  ggplot(., aes(x = thresh_tests, y = value, fill = samp_n_tests, color = type)) +
  facet_wrap(~onelinelabel, nrow = 2, scales = "free") +
  geom_boxplot(alpha = 0.9) +
  geom_hline(yintercept = 0, color = "red") +
  scale_color_manual(values = c("black", "grey47"), name = " ") +
  scale_fill_manual(values = pal_sampsize, name = "Sample Size") +
  labs(x = "Distance level", y = "Estimates of theta", subtitle = "Nonparametric") +
  theme_bw(base_size = 10) -> nonpar_bxplts

par_glm %>% 
  mutate(Original = theta_hat - theta,
         Corrected = theta_bar - theta) %>% 
  dplyr::select(thresh_tests, samp_n_tests, Original, Corrected) %>% 
  pivot_longer(cols = c(Original, Corrected), names_to = "type") %>% 
  filter(., !is.infinite(value)) %>% 
  mutate(thresholdsep = factor(ifelse(thresh_tests<500, "lower", "extremes"), levels = c("lower", "extremes")),
         onelinelabel = paste0("n = ", samp_n_tests, "-", thresholdsep),
         onelinelabel = factor(onelinelabel, levels = c(lowlabs, extlabs)),
         samp_n_tests = factor(samp_n_tests),
         thresh_tests = factor(thresh_tests)) %>% 
  ggplot(., aes(x = thresh_tests, y = value, fill = samp_n_tests, color = type)) +
  facet_wrap(~onelinelabel, nrow = 2, scales = "free") +
  geom_boxplot(alpha = 0.9) +
  geom_hline(yintercept = 0, color = "red") +
  scale_color_manual(values = c("black", "grey"), name = " ") +
  scale_fill_manual(values = pal_sampsize, name = "Sample Size") +
  labs(x = "Distance level", y = "Estimates of theta", subtitle = "Parametric") +
  theme_bw(base_size = 10) -> par_bxplts

bxplts_legend <- get_legend(par_bxplts)

bxplts <- plot_grid(nonpar_bxplts+ theme(legend.position = "none"),
          par_bxplts + theme(legend.position = "none"), nrow = 2)

plot_grid(bxplts, bxplts_legend, ncol = 2, rel_widths = c(1, 0.1))
  
```


```{r eval=FALSE, fig.height=6, fig.width=12}

corr_a %>% 
  mutate(samp_n_tests = factor(samp_n_tests),
         thresh_tests = factor(thresh_tests)) %>% 
  mutate(labelsamp = paste("n =", samp_n_tests),
         labelsamp = factor(labelsamp, levels = c("n = 80", "n = 200", "n = 500", "n = 800", "n = 1000", "n = 1600"))) %>%
  ggplot(., aes(x = thresh_tests, y = value, fill = type)) +
  facet_wrap(~labelsamp, nrow=1) +
  geom_hline(yintercept = 0, color = "red") +
  geom_boxplot(alpha = 0.9) +
  scale_fill_manual(values = c("grey47", "white"), name = "") +
  labs(x = "Distance level", y = "Estimated theta", title = corr_a$correctiontype[1]) +
  theme_bw() +
  # scale_y_continuous(limits = quantile(corr_a$value, c(0.1, 0.9))) +
  theme(legend.position = "right") -> a

        
corr_b %>% 
  mutate(samp_n_tests = factor(samp_n_tests),
         thresh_tests = factor(thresh_tests)) %>% 
  mutate(labelsamp = paste("n =", samp_n_tests),
         labelsamp = factor(labelsamp, levels = c("n = 80", "n = 200", "n = 500", "n = 800", "n = 1000", "n = 1600"))) %>%
  ggplot(., aes(x = thresh_tests, y = value, fill = type)) +
  facet_wrap(~labelsamp, nrow=1) +
  geom_hline(yintercept = 0, color = "red") +
  geom_boxplot(alpha = 0.9) +
  scale_fill_manual(values = c("grey47", "white"), name = "") +
  labs(x = "Distance level", y = "Estimated theta", title = corr_b$correctiontype[1]) +
  theme_bw() +
  # scale_y_continuous(limits = quantile(corr_b$value, c(0.1, 0.9))) +
  theme(legend.position = "right") -> b

plot_grid(a, b, nrow = 2)
        
```


```{r eval = FALSE, fig.width=10}
corr_b %>% 
  bind_rows(., corr_a) %>% 
  right_join(., thetas) %>%
  group_by(thresh_tests, samp_n_tests, type, correctiontype) %>% 
  summarize(Eval_theta_hat = mean(value),
            theta = mean(theta),
            bias = Eval_theta_hat - theta) %>% 
  mutate(samp_n_tests = factor(samp_n_tests),
         thresh_tests = factor(thresh_tests)) %>% 
  mutate(labelsamp = paste("n =", samp_n_tests),
         labelsamp = factor(labelsamp, levels = c("n = 80", "n = 200", "n = 500", "n = 800", "n = 1000", "n = 1600"))) %>% 
  mutate(bootcat = case_when(type == "Corrected" & correctiontype == "Nonparametric" ~ "NP - C",
                             type == "Corrected" & correctiontype == "Parametric" ~ "P - C",
                             type == "Original" & correctiontype == "Nonparametric" ~ "NP - UC",
                             type == "Original" & correctiontype == "Parametric" ~ "P - UC")) %>% 
  ggplot(., aes(y = bias, x = thresh_tests)) +
  facet_wrap(~labelsamp) +
  geom_jitter(aes(color = bootcat), size = 4, alpha = 0.8, width = 0.1) +
  geom_hline(yintercept = 0, color = "red") +
  scale_color_manual(values = pal_bias, name = "") +
  labs(x = "Long-distance level", y = "Bias") +
  theme_bw()
```



Nonparametric bootstrap correction for both the GLM Lomax and GP

```{r fig.width=10, fig.height=4}
dir_scenario <- "allinone_original"
load(paste0("Ch3_samplesize/", dir_scenario, "/allin1df.RData"))

# allin1df %>%
#   ggplot(., aes(x = factor(thresh_tests), y = log(gp_theta_hat/theta))) +
#   geom_hline(yintercept = 0, color = "red") +
#   geom_boxplot() -> a
# 
# allin1df %>%
#   ggplot(., aes(x = factor(thresh_tests), y = log(gp_theta_bar/theta))) +
#   geom_hline(yintercept = 0, color = "red") +
#   geom_boxplot() -> b
# 
# plot_grid(a,b, ncol = 2)
```

```{r Fig4, fig.width=6, fig.height=6}

allin1df %>%
  dplyr::select(., thresh_tests, samp_n_tests, gp_theta_hat, gp_theta_bar, theta) %>%
  mutate(original = log(gp_theta_hat/theta),
         corrected = log(gp_theta_bar/theta)) %>%
  pivot_longer(., cols = c(original, corrected), names_to = "type", values_to = "theta_val") %>%
  drop_na() %>%
  mutate(thresh_tests = factor(thresh_tests),
         samp_n_tests = factor(samp_n_tests)) %>% 
  mutate(labelsamp = paste("n =", samp_n_tests),
         labelsamp = factor(labelsamp, levels = c("n = 80", "n = 200", "n = 500", "n = 800", "n = 1000", "n = 1600"))) %>%
  ggplot(., aes(x = thresh_tests, y = theta_val, color = type, fill = type)) +
  facet_wrap(~labelsamp, nrow = 3) +
  geom_boxplot() +
  scale_color_manual(values = dens_cols[c(1,4)], name = "Bias") +
  scale_fill_manual(values = dens_cols[c(2,3)], name = "Bias") +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  labs(y = TeX(r'($log(\hat{\theta} / \theta)$)'), x = "Distance Level Estimated") +
  theme_bw()
ggsave("Ch3_samplesize/Figures/Figure4.png")
```

```{r Figure5, fig.width=12, fig.height=4}

i_threshold <- 50

allin1df %>%
  dplyr::select(., thresh_tests, samp_n_tests, gp_theta_hat, gp_theta_bar, theta) %>%
  mutate(original = log(gp_theta_hat/theta),
         corrected = log(gp_theta_bar/theta)) %>%
  pivot_longer(., cols = c(original, corrected), names_to = "type", values_to = "theta_val") %>%
  drop_na() %>%
  mutate(thresh_tests = factor(thresh_tests),
         samp_n_tests = factor(samp_n_tests)) -> readyplot_df

baseplot_fx <- function(i_threshold){readyplot_df %>% 
  filter(., thresh_tests == i_threshold) %>% 
  ggplot(., aes(x = samp_n_tests, y = theta_val, color = type, fill = samp_n_tests)) +
  # facet_wrap(~thresh_tests, scales = "free", ncol=4) +
  geom_boxplot() +
  scale_color_manual(values = c("black", "grey"), name = "Estimator") +
  scale_fill_manual(values = pal_sampsize, name = "Sample Size") +
  geom_hline(yintercept = 0, color = "red") +
  labs(y = "Theta ratio", subtitle = paste("Dist. level =", i_threshold)) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.x = element_blank())}


baseplot <- baseplot_fx(50) +
  theme(legend.position = "right",
        legend.box = "horizontal") +
  guides(fill = guide_legend(ncol = 2))

baselegend <- get_legend(baseplot)

# Distance level plots

t50 <- baseplot_fx(50)
t100 <- baseplot_fx(100)
t150 <- baseplot_fx(150)
t250 <- baseplot_fx(250)
t500 <- baseplot_fx(500)
t750 <- baseplot_fx(750)
t1000 <- baseplot_fx(1000)


toprow <- plot_grid(t50, t100, t150, t250, nrow = 1) 
bottomrow <- plot_grid(t500, t750, t1000, baselegend, nrow = 1)

plot_grid(toprow, bottomrow, nrow=2)
ggsave("Ch3_samplesize/Figures/Figure5.png")

```


```{r eval = FALSE, fig.width=12, fig.height=3}

allin1df %>%
  dplyr::select(., thresh_tests, samp_n_tests, lomax_theta_hat, lomax_theta_bar, theta) %>%
  mutate(original = lomax_theta_hat - log(theta),
         corrected = lomax_theta_bar - log(theta)) %>%
  pivot_longer(., cols = c(original, corrected), names_to = "type", values_to = "theta_val") %>%
  drop_na() %>%
  ggplot(., aes(x = factor(thresh_tests), y = theta_val, color = type)) +
  facet_wrap(~samp_n_tests, nrow = 1) +
  geom_boxplot() +
  geom_hline(yintercept = 0, color = "red") +
  theme_bw()
```

```{r eval=FALSE}

allin1df %>%
  dplyr::select(., thresh_tests, samp_n_tests, lomax_theta_hat, lomax_theta_bar, theta) %>%
  mutate(original = lomax_theta_hat,
         corrected = lomax_theta_bar) %>%
  pivot_longer(., cols = c(original, corrected), names_to = "type", values_to = "theta_val") %>%
  drop_na() %>%
  group_by(thresh_tests, samp_n_tests, type) %>%
  summarise(ExpVal_theta_hat = mean(theta_val),
            theta = log(mean(theta)),
            bias = ExpVal_theta_hat - theta) %>%
  ggplot(., aes(x = thresh_tests, y = bias, color = type)) +
  facet_wrap(~samp_n_tests) +
  geom_point() +
  theme_bw()


allin1df %>%
  dplyr::select(., thresh_tests, samp_n_tests, gp_theta_hat, gp_theta_bar, theta) %>%
  mutate(original = gp_theta_hat,
         corrected = gp_theta_bar) %>%
  pivot_longer(., cols = c(original, corrected), names_to = "type", values_to = "theta_val") %>%
  drop_na() %>%
  group_by(thresh_tests, samp_n_tests, type) %>%
  summarise(ExpVal_theta_hat = mean(theta_val),
            theta = mean(theta),
            bias = ExpVal_theta_hat - theta) %>%
  ggplot(., aes(x = thresh_tests, y = bias, color = type)) +
  facet_wrap(~samp_n_tests) +
  geom_point() +
  theme_bw()

```


