

load("paper/simple_exp_runs.RData")


library(fitdistrplus)
library(ggplot2)
library(dplyr)


# Fit a Weibull distribution to the dispersal kernels generated by each of the models


null_weibull <- fitdist(null_dispersal$dispersal, distr = "weibull")

null_weibull$estimate
plot(null_weibull)


indiv_weibull <- fitdist(indiv_dispersal$dispersal, distr = "weibull")

indiv_weibull$estimate
plot(indiv_weibull)

fam_weibull <- fitdist(fam_dispersal$dispersal, distr = "weibull")

fam_weibull$estimate
plot(fam_weibull)



# Long distance dispersal calculations

null_dispersal %>%
  filter(., dispersal >= 500) %>%
  group_by(., id) %>%
  summarize(max_d = max(dispersal),
            n_ldd = n(),
            prop_ldd = n_ldd/10000)

indiv_dispersal %>%
  filter(., dispersal >= 500) %>%
  group_by(., id) %>%
  summarize(max_d = max(dispersal),
            n_ldd = n(),
            prop_ldd = n_ldd/10000)

fam_dispersal %>%
  filter(., dispersal >= 500) %>%
  group_by(., id) %>%
  summarize(max_d = max(dispersal),
            n_ldd = n(),
            prop_ldd = n_ldd/10000)


# Interesting that not all individuals produce LDD
# For supplement, break down dispersal kernel by individual and family group. Panel to compare. Show clear variation in kernels produced by different individuals or groups.
# For manuscript, report table with averages for movement rates, etc.
indiv_dispersal %>%
  #filter(., id == "30") %>%
  ggplot(., aes(x = dispersal)) +
  facet_wrap(~id, nrow=2) +
  geom_histogram()




